// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package freetype

const (
	Version     = "v1.0.1"
	GitCommit   = "4e73317"          // the commit JUST BEFORE the release
	VersionDate = "2023-03-29 04:22" // UTC
)
