# Copyright 2010 The Freetype-Go Authors. All rights reserved.
# Use of this source code is governed by your choice of either the
# FreeType License or the GNU General Public License version 2 (or
# any later version), both of which can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=freetype-go.googlecode.com/hg/freetype/raster
GOFILES=\
	geom.go\
	paint.go\
	raster.go\

include $(GOROOT)/src/Make.pkg

